### PR TITLE
adding oracle script with miden-client setup

### PR DESCRIPTION
**Pull request by harsh-ps-2003**
The miden-client wrapper CLI for interacting with the miden network using Pragma Oracle with MASM contract!

### CODE REVIEW

**Comment by harsh-ps-2003** [comment]
@EvolveArt please mention all the things discussed in the call!

**Comment by EvolveArt** [comment]
> @EvolveArt please mention all the things discussed in the call!

So to summarize, we just want scripts that should do the following:
- Create oracle account on Miden testnet (or local devnet?)
- Execute the transaction script to push data on the oracle account
- Read data from the oracle account using the `read_data` procedure

A few other points that were mentionned:
1. `publish_data` should include a signature verification to ensure only a specific operator is allowed to publish data, later on this can be extended through a `PublisheRegistry` concept.
2. We need to find a way to encode an ASCII string in a `u64`. I doubt this is possible so we might have to use storage maps or a custom library to handle long strings, to be discussed w/ Miden. A temporary solution for now is just to have some id for a given pair e.g 1 -> BTC/USD, 2-> ETH/USD..

**Comment by EvolveArt** [comment]
@harsh-ps-2003 lets merge that first version, wdyt ?

**Comment by harsh-ps-2003** [comment]
@EvolveArt yup! i dont like large PRs myself. we can merge tomorrow I guess!

**Pull request merged**
